### ISSUE TITLE
Error: Cannot find module '@tailwindcss/line-clamp'

### ISSUE THREAD

**Issue by olivsinz** [shopperlabs/framework#118]
It occurs when running

`npm run dev`

During installation.

`
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module '@tailwindcss/line-clamp'
Require stack:
- ..\shoppertest\vendor\shopper\framework\tailwind.config.js
- ..\shoppertest\tailwind.config.js
- ..\shoppertest\node_modules\tailwindcss\lib\lib\setupTrackingContext.js
- ..\shoppertest\node_modules\tailwindcss\lib\index.js
- ..\shoppertest\webpack.mix.js
- ..\shoppertest\node_modules\laravel-mix\setup\webpack.config.js
- ..\shoppertest\node_modules\webpack-cli\lib\webpack-cli.js
- ..\shoppertest\node_modules\webpack-cli\lib\bootstrap.js
- ..\shoppertest\node_modules\webpack-cli\bin\cli.js
- ..\shoppertest\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (..\shoppertest\vendor\shopper\framework\tailwind.config.js:62:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at processResult (..\shoppertest\node_modules\webpack\lib\NormalModule.js:758:19)
    at ..\shoppertest\node_modules\webpack\lib\NormalModule.js:860:5
    at ..\shoppertest\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at ..\shoppertest\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (..\shoppertest\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (..\shoppertest\node_modules\postcss-loader\dist\index.js:142:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
`

**Comment by olivsinz** [comment]
The fix can be to notify in the doc to add the @tailwindcss/line-clamp plugin.

**Comment by olivsinz** [comment]
Pull request link:

https://github.com/shopperlabs/laravelshopper.dev/pull/1

**Comment by mckenziearts** [comment]
Fixed
